---
# These settings are synced to GitHub by https://probot.github.io/apps/settings

repository:
  description: This Cookiecutter Template can be used to initialize an opinionated project structure for an Ansible Collection.

  has_issues: true

  has_projects: false

  has_wiki: false

  has_downloads: false

  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging.
  allow_squash_merge: false

  # Either `true` to allow merging pull requests with a merge commit, or `false` to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging.
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true

  # Whenever there are new changes available in the base branch, present an "update branch" option in the pull request.
  allow_update_branch: true

# Labels: define labels for Issues and Pull Requests
labels:
  # Pull Request Status
  - name: pending code review
    color: "#0075CA"
    description: null

  - name: pending qa
    color: "#7057FF"
    description: null

  - name: changes requested
    color: "#FBCA04"
    description: null

  - name: approved
    color: "#17F352"
    description: null

  - name: blocked
    color: "#B60205"
    description: null

  - name: deferred
    color: "#C5DEF5"
    description: null

  # Issue Types
  - name: feature
    color: "#17F352"
    description: null

  - name: bug
    color: "#D73A4A"
    description: null

  - name: refactor
    color: "#C5DEF5"
    description: null

  - name: documentation
    color: "#0075CA"
    description: null

# https://docs.github.com/en/rest/reference/repos#add-a-repository-collaborator for available options
# Collaborators: give specific users access to this repository.
collaborators:
  - username: snapp
  - username: brandor5
  - username: rhjhunt
  - username: markknittel
  - username: daleroux

# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches
branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        # dismissal_restrictions: null
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        checks: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true
      # Permits force pushes to the protected branch by anyone with write access to the repository
      allow_force_pushes: false
      # Allows deletion of the protected branch by anyone with write access to the repository.
      allow_deletions: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions: null
