---

ci:
  autoupdate_branch: main
  autoupdate_schedule: weekly
  autoupdate_prs: true

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        exclude: .*\.github/.*|.*/galaxy.yml|.*cookiecutter.*/.ansible-lint|.*cookiecutter.*/meta/main.yml|.*cookiecutter.*/playbooks/.*.yml|.*cookiecutter.*/tasks/set_vars.yml  # yamllint disable-line rule:line-length

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
        exclude: hooks/.*
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        exclude: .*\.github/.*|.*/galaxy.yml|.*cookiecutter.*/.ansible-lint|.*cookiecutter.*/meta/main.yml|.*cookiecutter.*/playbooks/.*.yml|.*cookiecutter.*/tasks/set_vars.yml  # yamllint disable-line rule:line-length
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        exclude: ^cookiecutter.json$
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v7.2.0
    hooks:
      - id: cspell
