---

dictionaryDefinitions:
  - name: Spellcheck Overrides
    path: ./cspell_dictionary.txt
    addWords: true

dictionaries:
  - overrides

words:
  - "CODEOWNERS"
  - "antsibull"
  - "boto"
  - "cliconf"
  - "cookiecutter"
  - "cookiecutterrc"
  - "devel"
  - "docsite"
  - "elif"
  - "endraw"
  - "esac"
  - "fqcn"
  - "fnmatch"
  - "gruntfuggly"
  - "hostvars"
  - "httpapi"
  - "HTTPAPI"
  - "Libera"
  - "netcommon"
  - "netconf"
  - "noqa"
  - "notesdir"
  - "rstcheck"
  - "snapp"

ignorePaths:
  - "**/.github/CODEOWNERS"
  - "**/.github/settings.yml"
  - "**/.gitignore"
  - "**/cspell.config.yml"
