---
# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

# NOTE: The namespace of the collection.
namespace: "{{ cookiecutter.namespace }}"

# NOTE: The name of the collection.
name: "{{ cookiecutter.collection_name }}"

# NOTE: The version of the collection.
version: "{{ cookiecutter.version }}"

# The path to the Markdown (.md) readme file.
readme: README.md

# NOTE: A list of the collection's content authors.
authors:
  - "{{ cookiecutter.author }}"

# NOTE: A short summary description of the collection.
description: "{{ cookiecutter.collection_description }}"

{% if cookiecutter.license != 'none' -%}
# NOTE: Either a single license or a list of licenses for content inside of a collection.
# license:
#   - "{{ cookiecutter.license }}"

# NOTE: The path to the license file for the collection.
license_file: "LICENSE"
{%- else -%}
# NOTE: Either a single license or a list of licenses for content inside of a collection.
# license:
#   - GPL-3.0-or-later

# NOTE: The path to the license file for the collection.
# license_file: ""
{%- endif %}

# NOTE: A list of tags you want to associate with the collection for indexing/searching.
tags:
  - "{{ cookiecutter.tag }}"

# NOTE: The list of collection dependencies this collection requires to be installed for it to be usable.
# dependencies: {}

# NOTE: The URL of the originating SCM repository
repository: "{{ cookiecutter.scm_repository }}"

# NOTE: The URL to any online docs
# documentation: "{{ cookiecutter.scm_repository }}/wiki"

# NOTE: The URL to the homepage of the collection/project
# homepage: "{{ cookiecutter.scm_repository }}"

# NOTE: The URL to the collection issue tracker
issues: "{{ cookiecutter.scm_repository }}/issues"

# NOTE: The build ignore list that should not be included in the build artifact.
build_ignore:
  - .gitignore
  - .github
  - '*/.gitkeep'
  - .pre-commit-config.yaml
  - .vscode{% if cookiecutter.enable_antsibull_changelog %}
  - changelogs/.plugin-cache.yaml{% endif %}

# A dict controlling use of manifest directives used in building the collection artifact.
# manifest: null
