---
# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: "{{ cookiecutter.namespace }}"

name: "{{ cookiecutter.collection_name }}"

version: "{{ cookiecutter.version }}"

readme: README.md

authors:
  - "{{ cookiecutter.author }}"

description: "{{ cookiecutter.description }}"

license:
  - "GPL-3.0-or-later"

license_file: "LICENSE"

# TODO: Add tags for indexing/searching this collection
#
# A list of tags you want to associate with the collection for indexing/searching.
# A tag name has the same character requirements as `namespace` and `name`
tags:
  - "{{ cookiecutter.tag }}"

# Best practice is for collections to work as standalone, independent units, depending only on ansible-core.
# https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_shared.html#listing-collection-dependencies
# dependencies: {}

# NOTE: The URL of the originating SCM repository
repository: "{{ cookiecutter.scm_repository }}"

# NOTE: The URL to any online docs
# documentation: "{{ cookiecutter.scm_repository }}/wiki"

# NOTE: The URL to the homepage of the collection/project
# homepage: "{{ cookiecutter.scm_repository }}"

# NOTE: The URL to the collection issue tracker
issues: "{{ cookiecutter.scm_repository }}/issues"

# `build_ignore` is mutually exclusive with `manifest`
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
build_ignore:
  - .gitignore
  - .github
  - '*/.gitkeep'
  - .pre-commit-config.yaml
  - .vscode
  - changelogs/.plugin-cache.yaml

# `manifest` is mutually exclusive with `build_ignore`
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#manifest-directives
# manifest: null
