---
# https://ansible.readthedocs.io/projects/molecule/podman/#config-playbook

dependency:
  name: galaxy
  options:
    requirements-file: ../requirements.yml

provisioner:
  name: ansible
  playbooks:
    create: ../utils/playbooks/create.yml
    converge: ../utils/playbooks/converge.yml
    destroy: ../utils/playbooks/destroy.yml
  options:
    extra-vars: 'playbook={{cookiecutter.role_name}}'

driver:
  name: default
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

# NOTE: modify the list of containers for molecule to test on
# https://ansible.readthedocs.io/projects/molecule/configuration/#platforms
platforms:
  - name: ubi8
    image: registry.access.redhat.com/ubi8/ubi-init:latest
  - name: ubi9
    image: registry.access.redhat.com/ubi9/ubi-init:latest
