---
# See: https://github.com/ansible/ansible-lint

name: ansible-lint

on:
  # Run against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
  pull_request:
  # Run once per day to ensure that even if there haven't been commits that we are still testing against latest version of ansible-lint
  schedule:
    - cron: '0 4 * * *'

jobs:
  lint:
    name: Lint Ansible
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@main

      - name: Run Ansible Linter
        uses: ansible/ansible-lint-action@main
