---

name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run pre-commit Linter
        uses: pre-commit/action@v3.0.0

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run cspell Spell Check
        uses: streetsidesoftware/cspell-action@v3
        with:
          config: cspell.config.yml
