---

name: CI

on:
  # Run against all pushes (direct commits, also merged PRs)
  push:
  # Run against all Pull Requests to the main branch
  pull_request:
    branches: [main]
  # Run once a week to ensure that even if there haven't been commits that we are still testing against latest version of GitHub Actions
  # See: https://crontab.guru
  schedule:
    - cron: '15 5 * * 1'
  # Enable manual pipeline execution
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main

      - name: Run pre-commit Linter
        uses: pre-commit/action@main

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main

      - name: Run cspell Spell Check
        uses: streetsidesoftware/cspell-action@main
        with:
          config: cspell.config.yml

  cookiecutter:
    needs: [lint, spellcheck]
    name: cookiecutter (${{ matrix.extra_context }})
    strategy:
      matrix:
        extra_context:
          - defaults
          - no_license
          - no_changelog
          - no_license_or_changelog

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
        with:
          path: template

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install cookiecutter pre-commit

      - name: Configure cookiecutter variable overrides
        shell: bash
        run: |
          cat > config.yml <<EOF
          default_context:
          $(case "${{ matrix.extra_context }}" in
            no_license)
            echo '  license: none'
            ;;
            no_changelog)
            echo '  license: Apache-2.0'
            echo '  enable_antsibull_changelog: false'
            ;;
            no_license_or_changelog)
            echo '  license: none'
            echo '  enable_antsibull_changelog: false'
            ;;
          esac)
          EOF

      - name: Generate Ansible collection from template
        shell: bash
        run: |
          cat <<EOF
          Running cookiecutter with the following variable overrides:

          $(cat config.yml)

          EOF
          cookiecutter --no-input --config-file config.yml template

      - name: Run pre-commit Linter against generated collection
        run: |
          cd name/example
          git init
          git add .
          pre-commit run --all-files
